### PR TITLE
adjusted url declarations

### PR DESCRIPTION
**Pull request by gekkedev**
also added @connect declaration to prevent triggering warnings by exceeding the granted permissions & suggested version bump

### CODE REVIEW

**Comment by Tithen-Firion** [comment]
As far as I know `@connect` is used by Tampermonkey only but sure, we can add it.
But don't skip the protocol, it still matches `http://example.com/://steamtradematcher.com/`.

**Comment by gekkedev** [comment]
I noticed the declarations were either http-specific or https-specific, which may cause unexpected behavior when changes occur on serverside. So, what about `http*://`?

**Comment by Tithen-Firion** [comment]
It still matches `http://example.com/://steamtradematcher.com/`. You can do it with regular expressions. 

But forget `@include`. Just replace it with [`@match`](https://developer.chrome.com/extensions/match_patterns) and we're good (documentations of Grease-/Violent-/Tampermonkey link to that page). It's safer than `@include` and doesn't require RegExp. 
As for [`@connect`](https://tampermonkey.net/documentation.php#_connect) I think it should be just `// @connect steamtradematcher.com`.

**Comment by gekkedev** [comment]
Tried `@match` without protocol but only `@match *://` will work. According to the docs it will only get enabled with `http` or `https`. I additionally tested `example.com/://steamtradematcher.com/` and the script did not get enabled in Tampermonkey.
See my Tampermonkey/Chrome tested suggestion.

**Pull request merged**
